version: '3.8'

services:
  app:
    build: 
      context: .
    environment:
      PHP_FPM_POOL_NAME: "app"
      SSL_MODE: "off"
      AUTORUN_ENABLED: true
      AUTORUN_LARAVEL_CONFIG_CACHE: true  
      AUTORUN_LARAVEL_EVENT_CACHE: true 
      AUTORUN_LARAVEL_MIGRATION: "false"
      AUTORUN_LARAVEL_ROUTE_CACHE: true
      AUTORUN_LARAVEL_STORAGE_LINK: true
      AUTORUN_LARAVEL_VIEW_CACHE: true
      ASSET_URL: '${ASSET_URL}'
      APP_NAME: '${APP_NAME}'
      APP_ENV: '${APP_ENV}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      APP_URL: '${APP_URL}'
      APP_LOCALE: '${APP_LOCALE}'
      APP_FALLBACK_LOCALE: '${APP_FALLBACK_LOCALE}'
      APP_FAKER_LOCALE: '${APP_FAKER_LOCALE}'
      APP_MAINTENANCE_DRIVER: '${APP_MAINTENANCE_DRIVER}'
      BCRYPT_ROUNDS: '${BCRYPT_ROUNDS}'
      LOG_CHANNEL: '${LOG_CHANNEL}'
      LOG_STACK: '${LOG_STACK}'
      LOG_DEPRECATIONS_CHANNEL: '${LOG_DEPRECATIONS_CHANNEL}'
      LOG_LEVEL: '${LOG_LEVEL}'
      DB_CONNECTION: '${DB_CONNECTION}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      SESSION_DRIVER: '${SESSION_DRIVER}'
      SESSION_LIFETIME: '${SESSION_LIFETIME}'
      SESSION_ENCRYPT: '${SESSION_ENCRYPT}'
      SESSION_PATH: '${SESSION_PATH}'
      SESSION_DOMAIN: '${SESSION_DOMAIN}'
      BROADCAST_CONNECTION: '${BROADCAST_CONNECTION}'
      FILESYSTEM_DISK: '${FILESYSTEM_DISK}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION}'
      FILAMENT_FILESYSTEM_DISK: '${FILAMENT_FILESYSTEM_DISK}'
      CACHE_STORE: '${CACHE_STORE}'
      CACHE_PREFIX: '${CACHE_PREFIX}'
      MAIL_MAILER: '${MAIL_MAILER}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_ENCRYPTION: '${MAIL_ENCRYPTION}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_DEFAULT_REGION: '${AWS_DEFAULT_REGION}'
      AWS_BUCKET: '${AWS_BUCKET}'
      AWS_ENDPOINT: '${AWS_ENDPOINT}'
      AWS_USE_PATH_STYLE_ENDPOINT: '${AWS_USE_PATH_STYLE_ENDPOINT}'
      VITE_APP_NAME: '${APP_NAME}'